### ISSUE TITLE
Internal error raised upon request to count platforms with `detailed` set to true

### ISSUE THREAD

**Issue by jsmatias** [aiondemand/AIOD-rest-api#311] opened 2024-05-09 08:52 UTC
The API raises a `500 Error: internal server error` when a get request is made to _counts of platforms_ with the `detailed` parameter is set to `True`: `/counts/platforms/v1?detailed=true`

**How to reproduce it**
```
> curl -X 'GET' 'http://localhost/counts/platforms/v1?detailed=true'
{"detail":"Unexpected exception while processing your request. Please contact the maintainers: type object 'Platform' has no attribute 'platform'"}
```
**Cause**
When the `detailed` parameter set to `True` the API queries the DB to fetch the number of assets for each platform listed in the DB. Thus, this error occurs because `platform` has no field `platform` to be filtered from.

+ For any resource but `platforms`, e.g.: `datasets`:

✅`detailed=false` -> returns a int
```
> curl -X 'GET' 'http://localhost/counts/datasets/v1?detailed=false' 
10000
```
✅`detailed=true` -> returns a json
```
> curl -X 'GET' 'http://localhost/counts/datasets/v1?detailed=true' 
{
  "openml": 5069,
  "zenodo": 75799
}
 ```
+ For `platforms`

✅`detailed=false` -> returns a int
```
> curl -X 'GET' 'http://localhost/counts/platforms/v1?detailed=false'
7
```
❌`detailed=true`
```
> curl -X 'GET' 'http://localhost/counts/platforms/v1?detailed=true'
{"detail":"Unexpected exception while processing your request. Please contact the maintainers: type object 'Platform' has no attribute 'platform'"}
```

**Suggested solution**
 Add a condition to return the number of platforms for `aiod`, in case the `platform` field is not present in the asset. Ex.:
```
> curl -X 'GET' 'http://localhost/counts/platforms/v1?detailed=true'
{
  "aiod": 7
}
```

**Comment by andrejridzik** [comment] 2024-11-05 09:55
@PGijsbers This is a duplicate of already resolved #365

**Closed by andrejridzik** 2024-11-05 09:55 UTC
Labels: bug
