### ISSUE TITLE
Detailed platform counts error (in production)

### ISSUE THREAD

**Issue by PGijsbers** [aiondemand/AIOD-rest-api#319] opened 2024-05-24 14:03 UTC
The query `https://api.aiod.eu/counts/platforms/v1?detailed=true` fails with `{
  "detail": "Unexpected exception while processing your request. Please contact the maintainers: type object 'Platform' has no attribute 'platform'"
}`

I have not tested the reproducibility of this bug in other environments.

**Comment by andrejridzik** [comment] 2024-11-05 09:44
This is a duplicate of already resolved issue #365

**Closed by andrejridzik** 2024-11-05 09:44 UTC
Labels: bug
